// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: event/event.proto

package epb

import (
	uepb "github.com/micros-template/proto-event/pkg/uepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*EventMessage_UserEvent
	Event         isEventMessage_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	mi := &file_event_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventMessage) GetEvent() isEventMessage_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventMessage) GetUserEvent() *uepb.UserEvent {
	if x != nil {
		if x, ok := x.Event.(*EventMessage_UserEvent); ok {
			return x.UserEvent
		}
	}
	return nil
}

type isEventMessage_Event interface {
	isEventMessage_Event()
}

type EventMessage_UserEvent struct {
	UserEvent *uepb.UserEvent `protobuf:"bytes,1,opt,name=user_event,json=userEvent,proto3,oneof"`
}

func (*EventMessage_UserEvent) isEventMessage_Event() {}

var File_event_event_proto protoreflect.FileDescriptor

const file_event_event_proto_rawDesc = "" +
	"\n" +
	"\x11event/event.proto\x12\x03epb\x1a\x15user/user_event.proto\"I\n" +
	"\fEventMessage\x120\n" +
	"\n" +
	"user_event\x18\x01 \x01(\v2\x0f.uepb.UserEventH\x00R\tuserEventB\a\n" +
	"\x05eventB0Z.github.com/micros-template/proto-event/pkg/epbb\x06proto3"

var (
	file_event_event_proto_rawDescOnce sync.Once
	file_event_event_proto_rawDescData []byte
)

func file_event_event_proto_rawDescGZIP() []byte {
	file_event_event_proto_rawDescOnce.Do(func() {
		file_event_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_event_proto_rawDesc), len(file_event_event_proto_rawDesc)))
	})
	return file_event_event_proto_rawDescData
}

var file_event_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_event_proto_goTypes = []any{
	(*EventMessage)(nil),   // 0: epb.EventMessage
	(*uepb.UserEvent)(nil), // 1: uepb.UserEvent
}
var file_event_event_proto_depIdxs = []int32{
	1, // 0: epb.EventMessage.user_event:type_name -> uepb.UserEvent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_event_proto_init() }
func file_event_event_proto_init() {
	if File_event_event_proto != nil {
		return
	}
	file_event_event_proto_msgTypes[0].OneofWrappers = []any{
		(*EventMessage_UserEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_event_proto_rawDesc), len(file_event_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_event_proto_goTypes,
		DependencyIndexes: file_event_event_proto_depIdxs,
		MessageInfos:      file_event_event_proto_msgTypes,
	}.Build()
	File_event_event_proto = out.File
	file_event_event_proto_goTypes = nil
	file_event_event_proto_depIdxs = nil
}
