// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: user/user_event.proto

package uepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*UserEvent_UserCreated
	//	*UserEvent_UserUpdated
	//	*UserEvent_UserDeleted
	Event         isUserEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEvent) Reset() {
	*x = UserEvent{}
	mi := &file_user_user_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEvent) ProtoMessage() {}

func (x *UserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEvent.ProtoReflect.Descriptor instead.
func (*UserEvent) Descriptor() ([]byte, []int) {
	return file_user_user_event_proto_rawDescGZIP(), []int{0}
}

func (x *UserEvent) GetEvent() isUserEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *UserEvent) GetUserCreated() *UserCreated {
	if x != nil {
		if x, ok := x.Event.(*UserEvent_UserCreated); ok {
			return x.UserCreated
		}
	}
	return nil
}

func (x *UserEvent) GetUserUpdated() *UserUpdated {
	if x != nil {
		if x, ok := x.Event.(*UserEvent_UserUpdated); ok {
			return x.UserUpdated
		}
	}
	return nil
}

func (x *UserEvent) GetUserDeleted() *UserDeleted {
	if x != nil {
		if x, ok := x.Event.(*UserEvent_UserDeleted); ok {
			return x.UserDeleted
		}
	}
	return nil
}

type isUserEvent_Event interface {
	isUserEvent_Event()
}

type UserEvent_UserCreated struct {
	UserCreated *UserCreated `protobuf:"bytes,1,opt,name=user_created,json=userCreated,proto3,oneof"`
}

type UserEvent_UserUpdated struct {
	UserUpdated *UserUpdated `protobuf:"bytes,2,opt,name=user_updated,json=userUpdated,proto3,oneof"`
}

type UserEvent_UserDeleted struct {
	UserDeleted *UserDeleted `protobuf:"bytes,3,opt,name=user_deleted,json=userDeleted,proto3,oneof"`
}

func (*UserEvent_UserCreated) isUserEvent_Event() {}

func (*UserEvent_UserUpdated) isUserEvent_Event() {}

func (*UserEvent_UserDeleted) isUserEvent_Event() {}

type UserCreated struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Image            *string                `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Email            string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password         string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Verified         bool                   `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	TwoFactorEnabled bool                   `protobuf:"varint,7,opt,name=two_factor_enabled,json=twoFactorEnabled,proto3" json:"two_factor_enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserCreated) Reset() {
	*x = UserCreated{}
	mi := &file_user_user_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreated) ProtoMessage() {}

func (x *UserCreated) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreated.ProtoReflect.Descriptor instead.
func (*UserCreated) Descriptor() ([]byte, []int) {
	return file_user_user_event_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserCreated) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserCreated) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *UserCreated) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreated) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreated) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *UserCreated) GetTwoFactorEnabled() bool {
	if x != nil {
		return x.TwoFactorEnabled
	}
	return false
}

type UserUpdated struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Image            *string                `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Email            string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password         string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Verified         bool                   `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	TwoFactorEnabled bool                   `protobuf:"varint,7,opt,name=two_factor_enabled,json=twoFactorEnabled,proto3" json:"two_factor_enabled,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserUpdated) Reset() {
	*x = UserUpdated{}
	mi := &file_user_user_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdated) ProtoMessage() {}

func (x *UserUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdated.ProtoReflect.Descriptor instead.
func (*UserUpdated) Descriptor() ([]byte, []int) {
	return file_user_user_event_proto_rawDescGZIP(), []int{2}
}

func (x *UserUpdated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserUpdated) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserUpdated) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *UserUpdated) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpdated) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserUpdated) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *UserUpdated) GetTwoFactorEnabled() bool {
	if x != nil {
		return x.TwoFactorEnabled
	}
	return false
}

func (x *UserUpdated) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UserDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleted) Reset() {
	*x = UserDeleted{}
	mi := &file_user_user_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleted) ProtoMessage() {}

func (x *UserDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleted.ProtoReflect.Descriptor instead.
func (*UserDeleted) Descriptor() ([]byte, []int) {
	return file_user_user_event_proto_rawDescGZIP(), []int{3}
}

func (x *UserDeleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_user_user_event_proto protoreflect.FileDescriptor

const file_user_user_event_proto_rawDesc = "" +
	"\n" +
	"\x15user/user_event.proto\x12\x04uepb\"\xbc\x01\n" +
	"\tUserEvent\x126\n" +
	"\fuser_created\x18\x01 \x01(\v2\x11.uepb.UserCreatedH\x00R\vuserCreated\x126\n" +
	"\fuser_updated\x18\x02 \x01(\v2\x11.uepb.UserUpdatedH\x00R\vuserUpdated\x126\n" +
	"\fuser_deleted\x18\x03 \x01(\v2\x11.uepb.UserDeletedH\x00R\vuserDeletedB\a\n" +
	"\x05event\"\xdb\x01\n" +
	"\vUserCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x19\n" +
	"\x05image\x18\x03 \x01(\tH\x00R\x05image\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\x12,\n" +
	"\x12two_factor_enabled\x18\a \x01(\bR\x10twoFactorEnabledB\b\n" +
	"\x06_image\"\xfa\x01\n" +
	"\vUserUpdated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x19\n" +
	"\x05image\x18\x03 \x01(\tH\x00R\x05image\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\x12,\n" +
	"\x12two_factor_enabled\x18\a \x01(\bR\x10twoFactorEnabled\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAtB\b\n" +
	"\x06_image\"\x1d\n" +
	"\vUserDeleted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB+Z)10.1.20.149/dropping/proto-event/pkg/uepbb\x06proto3"

var (
	file_user_user_event_proto_rawDescOnce sync.Once
	file_user_user_event_proto_rawDescData []byte
)

func file_user_user_event_proto_rawDescGZIP() []byte {
	file_user_user_event_proto_rawDescOnce.Do(func() {
		file_user_user_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_event_proto_rawDesc), len(file_user_user_event_proto_rawDesc)))
	})
	return file_user_user_event_proto_rawDescData
}

var file_user_user_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_user_event_proto_goTypes = []any{
	(*UserEvent)(nil),   // 0: uepb.UserEvent
	(*UserCreated)(nil), // 1: uepb.UserCreated
	(*UserUpdated)(nil), // 2: uepb.UserUpdated
	(*UserDeleted)(nil), // 3: uepb.UserDeleted
}
var file_user_user_event_proto_depIdxs = []int32{
	1, // 0: uepb.UserEvent.user_created:type_name -> uepb.UserCreated
	2, // 1: uepb.UserEvent.user_updated:type_name -> uepb.UserUpdated
	3, // 2: uepb.UserEvent.user_deleted:type_name -> uepb.UserDeleted
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_user_event_proto_init() }
func file_user_user_event_proto_init() {
	if File_user_user_event_proto != nil {
		return
	}
	file_user_user_event_proto_msgTypes[0].OneofWrappers = []any{
		(*UserEvent_UserCreated)(nil),
		(*UserEvent_UserUpdated)(nil),
		(*UserEvent_UserDeleted)(nil),
	}
	file_user_user_event_proto_msgTypes[1].OneofWrappers = []any{}
	file_user_user_event_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_event_proto_rawDesc), len(file_user_user_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_event_proto_goTypes,
		DependencyIndexes: file_user_user_event_proto_depIdxs,
		MessageInfos:      file_user_user_event_proto_msgTypes,
	}.Build()
	File_user_user_event_proto = out.File
	file_user_user_event_proto_goTypes = nil
	file_user_user_event_proto_depIdxs = nil
}
